"""relacionamentoUnidadeFatura​

Revision ID: 0c8a50c7d2cf
Revises: d963df239688
Create Date: 2021-10-18 00:08:02.899432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8a50c7d2cf'
down_revision = 'd963df239688'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_consumidora_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_fatura_cliente_unidade_consumidora_id_unidade_consumidora'), 'unidade_consumidora', ['unidade_consumidora_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fatura_cliente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fatura_cliente_unidade_consumidora_id_unidade_consumidora'), type_='foreignkey')
        batch_op.drop_column('unidade_consumidora_id')

    # ### end Alembic commands ###
