"""faturaCliente​

Revision ID: 107b91a61045
Revises: c0fd5b8c2ae7
Create Date: 2021-10-17 22:09:56.293229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107b91a61045'
down_revision = 'c0fd5b8c2ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatura_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_consumo', sa.Float(), nullable=True),
    sa.Column('nome_titular', sa.String(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_leitura', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('energia_consumida', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fatura_cliente_id'), 'fatura_cliente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fatura_cliente_id'), table_name='fatura_cliente')
    op.drop_table('fatura_cliente')
    # ### end Alembic commands ###
