"""relacionamentoUnidadeUsuario​

Revision ID: d963df239688
Revises: 107b91a61045
Create Date: 2021-10-17 23:53:02.781828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd963df239688'
down_revision = '107b91a61045'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade_consumidora', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_unidade_consumidora_usuario_id_usuario'), 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade_consumidora', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_unidade_consumidora_usuario_id_usuario'), type_='foreignkey')

    # ### end Alembic commands ###
